---

install:
  - choco install strawberryperl
  - SET PATH=C:\Perl5\bin;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - perl -v
  - if not exist C:\Perl5 mkdir C:\Perl5
  - SET PERL5LIB=C:/Perl5/lib/perl5
  - SET PERL_LOCAL_LIB_ROOT=C:/Perl5
  - SET PERL_MB_OPT=--install_base C:/Perl5
  - SET PERL_MM_OPT=INSTALL_BASE=C:/Perl5
  - cpanm -n Alien::FFI
  - cpanm -n ExtUtils::CBuilder
  - cpanm -n FFI::CheckLib
  - cpanm -n Math::Int64
  - cpanm -n Win32::ErrorMode
  - cpanm -n Devel::PPPort  
  - cpanm -n constant

build: off

test_script:
  - perl Build.PL
  - Build --verbose
  - Build test --verbose

#cache:
#  - C:\Perl5

shallow_clone: true
